apiVersion: v1
kind: ServiceAccount
metadata:
  name: coach-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/replace-me-coach-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coach-worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/replace-me-coach-worker
