<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'; import PageHeading from '@/components/PageHeading.vue'; import { api, demoMode } from '@/services/api'; import { useCoachStore } from '@/stores/coach'
type Message = { role:'coach'|'you'; body:string; time:string }
const store=useCoachStore(); const started=ref(false), finished=ref(false), input=ref(''), busy=ref(false), connectionError=ref(''); const phase=ref(0); const phases=['Requirements','Estimation','High-level design','Deep dive','Wrap-up']; const messages=ref<Message[]>([]); let socket: WebSocket | undefined
const prompts=['Great start. Before drawing components, clarify the functional and non-functional requirements. Which two constraints will dominate this design?','Let’s put numbers behind it. Estimate peak write throughput and storage for one year. State your assumptions.','Walk me through your high-level design. Where does the request enter, and which components sit on the critical path?','Your primary region fails during a traffic spike. What breaks first, and how will the system recover?','Summarize your biggest trade-off and one improvement you would make with another week.']
const phaseLabel=computed(()=>phases[phase.value])
async function start(){busy.value=true; connectionError.value=''; try { const interview=await store.createInterview('Design a notification platform that delivers email, push, and SMS for 50 million users.'); started.value=true; messages.value=interview.messages.map(message=>({role:message.role==='interviewer'?'coach':'you',body:message.content,time:'Now'})); if(!demoMode) socket=api.interviewSocket(interview.id, message=>{messages.value.push({role:message.role==='interviewer'?'coach':'you',body:message.content,time:'Now'}); phase.value=Math.min(4,phase.value+1); if(message.content.toLowerCase().includes('scorecard'))finish()}, message=>connectionError.value=message) } catch(cause){connectionError.value=cause instanceof Error?cause.message:'The interview room could not be created.'} finally{busy.value=false}}
async function finish(){finished.value=true; try{await store.loadScorecard()}catch(cause){connectionError.value=cause instanceof Error?cause.message:'Your scorecard is still being prepared.'}}
function send(){const content=input.value.trim();if(!content)return; messages.value.push({role:'you',body:content,time:'Now'});input.value='';connectionError.value='';if(socket?.readyState===WebSocket.OPEN&&store.interview){socket.send(JSON.stringify({event_id:crypto.randomUUID(),type:'candidate.message',interview_id:store.interview.id,sequence:store.interview.sequence+messages.value.length,timestamp:new Date().toISOString(),payload:{content}}));return}if(!demoMode){connectionError.value='The live connection is not ready. Reopen the interview room and try again.';return}setTimeout(()=>{if(phase.value<4){phase.value++;messages.value.push({role:'coach',body:prompts[phase.value],time:'Now'})}else finish()},250)}
onBeforeUnmount(()=>socket?.close())
</script>
<template><div class="page interview-page"><PageHeading v-if="!started" eyebrow="PRACTICE UNDER PRESSURE" title="Think like a principal engineer" description="A realistic, adaptive system design interview—with pushback, follow-ups, and a scorecard that tells you exactly where to improve." />
    <section v-if="!started" class="interview-start"><div class="interview-hero"><span class="interview-orb">◉</span><span class="tag accent">Recommended for you</span><h2>Design a notification platform</h2><p>Multi-channel delivery at global scale, with reliability and cost constraints.</p><div class="interview-details"><div><strong>45</strong><span>minutes</span></div><div><strong>L6</strong><span>difficulty</span></div><div><strong>5</strong><span>dimensions</span></div></div><p v-if="connectionError" class="inline-error">{{ connectionError }}</p><button class="button primary" :disabled="busy" @click="start">{{busy?'Opening room…':'Enter interview room →'}}</button></div><aside class="card"><span class="eyebrow">YOU’LL BE ASSESSED ON</span><ul class="rubric"><li><span>01</span>Requirements & scope</li><li><span>02</span>Scale estimation</li><li><span>03</span>Architecture & data flow</li><li><span>04</span>Reliability & security</li><li><span>05</span>Communication</li></ul></aside></section>
  <section v-else-if="!finished" class="interview-room"><header><div><span class="live-dot"/> Live interview</div><strong>{{ phaseLabel }}</strong><span>38:24 remaining</span></header><div class="phase-track"><i v-for="(item,i) in phases" :key="item" :class="{ complete:i<phase, current:i===phase }"><span>{{ i<phase?'✓':i+1 }}</span><small>{{ item }}</small></i></div><div class="conversation"><article v-for="(message,i) in messages" :key="i" :class="message.role"><span>{{ message.role==='coach'?'N':'A' }}</span><div><small>{{ message.role==='coach'?'Nora · Interviewer':'You' }}</small><p>{{ message.body }}</p></div></article></div><p v-if="connectionError" class="inline-error room-error">{{connectionError}}</p><form class="message-box" @submit.prevent="send"><textarea v-model="input" rows="3" placeholder="Think aloud and explain your trade-offs…"/><div><span>Shift + Enter for new line</span><button class="button primary" :disabled="!input.trim()">Send answer ↑</button></div></form></section>
  <section v-else class="scorecard"><span class="result-orb">{{Math.round(store.scorecard?.overall||0)}}</span><p class="eyebrow">INTERVIEW COMPLETE</p><h1>Strong architecture instincts.</h1><p>{{store.scorecard?.strengths[0]||connectionError||'Your detailed scorecard is being prepared.'}}</p><div class="score-bars"><div v-for="item in [{n:'Scalability',v:store.scorecard?.scalability||0},{n:'Reliability',v:store.scorecard?.reliability||0},{n:'Security',v:store.scorecard?.security||0},{n:'Cost',v:store.scorecard?.cost||0},{n:'Communication',v:store.scorecard?.communication||0}]" :key="item.n"><span>{{item.n}}</span><div class="progress-track"><i :style="{width:`${item.v}%`}"/></div><strong>{{Math.round(item.v)}}</strong></div></div><div><button class="button" @click="started=false;finished=false;phase=0;messages=[];socket?.close()">Try another</button><RouterLink class="button primary" to="/progress">View progress →</RouterLink></div></section>
</div></template>
