<script setup lang="ts">import { computed, ref } from 'vue'; import { useCoachStore } from '@/stores/coach'; const store = useCoachStore(); const lesson = computed(() => store.session?.lesson); const sourceOpen = ref(false);</script>
<template><div class="page lesson-page" v-if="lesson">
  <div class="lesson-header"><RouterLink class="back-link" to="/today">← Today’s itinerary</RouterLink><span class="tag accent">Lesson · 2 of 4</span><h1>{{ lesson.title }}</h1><p>{{ lesson.eyebrow }}</p><div class="progress-track"><i style="width:54%"/></div></div>
  <div class="lesson-layout"><article class="lesson-content">
    <section v-for="(section, index) in lesson.sections" :key="section.title"><span class="section-number">0{{ index + 1 }}</span><h2>{{ section.title }}</h2><p>{{ section.body }}</p></section>
    <section><span class="section-number">04</span><h2>Reference architecture</h2><pre class="architecture" aria-label="Architecture diagram">{{ lesson.diagram }}</pre></section>
    <div class="lesson-panels"><section class="callout danger"><strong>Production pitfalls</strong><ul><li v-for="item in lesson.pitfalls" :key="item">{{ item }}</li></ul></section><section class="callout success"><strong>Keep this close</strong><ul><li v-for="item in lesson.cheatSheet" :key="item">{{ item }}</li></ul></section></div>
    <section class="sources"><button class="source-button" @click="sourceOpen = !sourceOpen"><span>▤</span><span><strong>{{ lesson.sources.length }} source used</strong><small>Uploaded knowledge was preferred for this lesson</small></span><span>{{ sourceOpen ? '⌃' : '⌄' }}</span></button><div v-if="sourceOpen" class="source-detail" v-for="source in lesson.sources" :key="source.id"><strong>{{ source.title }}</strong><span>{{ source.location }}</span><p>“{{ source.excerpt }}”</p></div></section>
    <div class="lesson-actions"><RouterLink class="button" to="/today">Save for later</RouterLink><RouterLink class="button primary" to="/quiz">Start knowledge check →</RouterLink></div>
  </article><aside class="lesson-outline card"><span class="eyebrow">IN THIS LESSON</span><a v-for="(section, i) in lesson.sections" :key="section.title" :href="`#section-${i}`"><span>0{{ i + 1 }}</span>{{ section.title }}</a><a href="#"><span>04</span>Reference architecture</a><div class="confidence"><p>How clear does this feel?</p><div><button aria-label="Not clear">1</button><button>2</button><button>3</button><button>4</button><button aria-label="Very clear">5</button></div></div></aside></div>
</div></template>
