<script setup lang="ts">
import { ref } from 'vue'; import { useCoachStore } from '@/stores/coach'; import PageHeading from '@/components/PageHeading.vue'; const store = useCoachStore(); const dragging = ref(false); const uploading = ref(false); const fileInput = ref<HTMLInputElement>()
async function upload(files: FileList | null) { const file=files?.[0]; if(!file)return; uploading.value=true; try { const item=await store.uploadDocument(file); poll(item.id) } finally { uploading.value=false; dragging.value=false } }
async function poll(id:string, attempts=0){if(attempts>=8)return;try{const item=await store.refreshDocument(id);if(item.status==='processing')setTimeout(()=>poll(id,attempts+1),2500)}catch{/* the visible processing state remains retryable */}}
async function remove(id:string){try{await store.deleteDocument(id)}catch(cause){alert(cause instanceof Error?cause.message:'The document could not be deleted.')}}
function drop(e: DragEvent) { upload(e.dataTransfer?.files || null) }
</script>
<template><div class="page library-page"><PageHeading eyebrow="YOUR KNOWLEDGE" title="Teach Nora what matters to you" description="Upload trusted material. Your coach will prefer it, cite it, and keep every answer grounded." />
  <section class="upload-zone" :class="{ dragging }" @dragover.prevent="dragging=true" @dragleave="dragging=false" @drop.prevent="drop"><input ref="fileInput" type="file" accept=".pdf,.md,.docx,.pptx" hidden @change="upload(($event.target as HTMLInputElement).files)"/><span class="upload-icon">↑</span><h2>{{ uploading ? 'Preparing your document…' : 'Drop a document here' }}</h2><p>PDF, Markdown, DOCX or PPTX · Up to 25 MB</p><button class="button" :disabled="uploading" @click="fileInput?.click()">{{ uploading ? 'Uploading…' : 'Choose a file' }}</button><small>Documents are isolated to your private workspace.</small></section>
  <section class="card library-list"><div class="section-heading"><div><span class="eyebrow">SOURCES</span><h2>Your library</h2></div><label class="search"><span>⌕</span><input placeholder="Search documents" aria-label="Search documents"/></label></div>
    <article v-for="doc in store.documents" :key="doc.id"><span class="file-icon">{{ doc.type === 'PDF' ? 'PDF' : doc.type.slice(0,3).toUpperCase() }}</span><div class="file-info"><strong>{{ doc.name }}</strong><p>{{ doc.size }} · {{ doc.uploadedAt }}</p></div><span class="status" :class="doc.status"><i/>{{ doc.status === 'indexed' ? `${doc.chunks} chunks indexed` : doc.status === 'processing' ? 'Processing' : 'OCR needed' }}</span><button class="more-button delete-button" :aria-label="`Delete ${doc.name}`" @click="remove(doc.id)">×</button></article>
  </section><aside class="trust-note"><span>⌾</span><div><strong>Grounded answers, visible sources</strong><p>Whenever Nora uses your material, the lesson includes the exact document and location. General model knowledge is clearly labelled.</p></div></aside>
</div></template>
