<script setup lang="ts">
import { computed, ref, watch } from 'vue'; import { useCoachStore } from '@/stores/coach'; import PageHeading from '@/components/PageHeading.vue'; import type { Preferences } from '@/types'; const store=useCoachStore(); const saved=ref(false); const form=ref<Preferences>(); watch(()=>store.preferences, value=>{if(value)form.value=structuredClone(value)}, {immediate:true}); const domainOptions=['AWS Architecture','System Design','Kubernetes','Algorithms','AI Engineering']; const initials=computed(()=>form.value?.name.split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase()||'L'); function toggleDomain(d:string){if(!form.value)return; const i=form.value.domains.indexOf(d); i>=0?form.value.domains.splice(i,1):form.value.domains.push(d)} async function save(){if(!form.value)return;await store.savePreferences(form.value);saved.value=true;setTimeout(()=>saved.value=false,2000)}
</script>
<template><div class="page preferences-page" v-if="form"><PageHeading eyebrow="PERSONALIZE YOUR COACH" title="Learning preferences" description="Nora uses these choices to shape your sessions, pacing, and reminders." />
  <form class="settings-grid" @submit.prevent="save"><section class="card settings-card"><div class="settings-title"><span class="avatar large">{{ initials }}</span><div><h2>Your profile</h2><p>How your coach addresses and guides you.</p></div></div><label>Name<input v-model="form.name" required/></label><label>Coaching mode<select v-model="form.mode"><option>Teacher</option><option>Mentor</option><option>Exam Coach</option><option>Interviewer</option><option>Architect</option></select></label></section>
  <section class="card settings-card"><div class="settings-title"><span class="setting-icon">◷</span><div><h2>Daily rhythm</h2><p>Set a schedule that fits your life.</p></div></div><label>Session length<select v-model.number="form.duration"><option :value="25">25 minutes</option><option :value="45">45 minutes</option><option :value="60">60 minutes</option></select></label><div class="field-row"><label>Reminder time<input v-model="form.notificationTime" type="time"/></label><label>Timezone<select v-model="form.timezone"><option>Asia/Bangkok</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option></select></label></div></section>
  <section class="card settings-card full"><div class="settings-title"><span class="setting-icon">⌁</span><div><h2>Learning domains</h2><p>Choose what belongs in your adaptive curriculum.</p></div></div><div class="domain-pills"><button v-for="d in domainOptions" :key="d" type="button" :class="{selected:form.domains.includes(d)}" @click="toggleDomain(d)"><span>{{form.domains.includes(d)?'✓':'+'}}</span>{{d}}</button></div></section>
  <section class="card settings-card full"><div class="settings-title"><span class="setting-icon">◌</span><div><h2>Notifications</h2><p>Get the right nudge, never the noise.</p></div></div><label class="toggle-row"><span><strong>In-app notifications</strong><small>Session updates, reviews, and coaching insights</small></span><input v-model="form.inApp" type="checkbox"/></label><label class="toggle-row"><span><strong>Email reminders</strong><small>Your daily itinerary and missed-session recovery</small></span><input v-model="form.email" type="checkbox"/></label></section>
  <footer class="settings-footer"><span v-if="saved" class="saved">✓ Preferences saved</span><button class="button primary">Save preferences</button></footer></form>
</div></template>
