<script setup lang="ts">
import { computed, ref } from 'vue'; import { useCoachStore } from '@/stores/coach'; import { demoMode } from '@/services/api'; import type { QuizResult } from '@/types'
const store = useCoachStore(); const index = ref(0); const responses = ref<Record<string,string>>({}); const checked = ref(false); const done = ref(false); const submitting = ref(false); const submitError = ref(''); const result = ref<QuizResult>()
const questions = computed(() => store.session?.questions || []); const question = computed(() => questions.value[index.value]); const correct = computed(() => normalize(responses.value[question.value?.id] || '').includes(normalize(question.value?.answer || '')) || normalize(question.value?.answer || '').includes(normalize(responses.value[question.value?.id] || '___'))); const score = computed(() => result.value ? Math.round(result.value.score / 100 * questions.value.length) : questions.value.filter(q => normalize(responses.value[q.id] || '').includes(normalize(q.answer)) || normalize(q.answer).includes(normalize(responses.value[q.id] || '___'))).length)
function normalize(value:string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim() }
function check() { if (responses.value[question.value.id]?.trim()) checked.value = true }
async function next() { if (index.value < questions.value.length - 1) { index.value++; checked.value = false; return } submitting.value = true; submitError.value = ''; try { result.value = await store.submitQuiz(responses.value); done.value = true } catch (cause) { submitError.value = cause instanceof Error ? cause.message : 'Your answers could not be submitted.' } finally { submitting.value = false } }
async function finishSession(){submitting.value=true;submitError.value='';try{await store.completeSession()}catch(cause){submitError.value=cause instanceof Error?cause.message:'Your session could not be completed.'}finally{submitting.value=false}}
</script>
<template><div class="page quiz-page">
  <template v-if="!done && question"><header class="quiz-top"><RouterLink class="back-link" to="/lesson">← Back to lesson</RouterLink><span>Question {{ index + 1 }} of {{ questions.length }}</span><div class="progress-track"><i :style="{ width: `${((index + (checked ? 1 : 0)) / questions.length) * 100}%` }"/></div></header>
  <main class="quiz-card"><span class="tag">{{ question.type.replace('_', ' ') }}</span><h1>{{ question.prompt }}</h1>
    <div v-if="question.options" class="answer-options"><button v-for="(option, i) in question.options" :key="option" :disabled="checked" :class="{ selected: responses[question.id] === option, correct: checked && option === question.answer, wrong: checked && responses[question.id] === option && option !== question.answer }" @click="responses[question.id] = option"><span>{{ String.fromCharCode(65 + i) }}</span>{{ option }}<i v-if="checked && option === question.answer">✓</i></button></div>
    <label v-else class="scenario-answer"><span>Your answer</span><textarea v-model="responses[question.id]" :disabled="checked" rows="5" placeholder="Think aloud. Explain the trade-off and your reasoning…" /></label>
    <section v-if="checked && demoMode" class="feedback" :class="correct ? 'right' : 'retry'"><div class="feedback-title"><span>{{ correct ? '✓' : '↻' }}</span><strong>{{ correct ? 'Exactly right' : 'Not quite — here’s the key' }}</strong></div><p>{{ question.explanation }}</p><p v-if="!correct && question.misconception" class="misconception"><strong>Watch for:</strong> {{ question.misconception }}</p></section>
    <section v-else-if="checked" class="feedback right"><div class="feedback-title"><span>✓</span><strong>Answer recorded</strong></div><p>Your coach will evaluate the full set together and update your mastery when you submit.</p></section><p v-if="submitError" class="inline-error">{{ submitError }}</p>
    <footer><span v-if="!checked" class="quiet">Choose an answer to continue</span><button v-if="!checked" class="button primary" :disabled="!responses[question.id]?.trim()" @click="check">{{ demoMode ? 'Check answer' : 'Record answer' }}</button><button v-else class="button primary" :disabled="submitting" @click="next">{{ submitting ? 'Submitting…' : index === questions.length - 1 ? 'Submit & see results' : 'Next question' }} →</button></footer>
  </main></template>
  <section v-else class="results-card"><span class="result-orb">{{ score === questions.length ? '★' : '↗' }}</span><p class="eyebrow">KNOWLEDGE CHECK COMPLETE</p><h1>{{ score === questions.length ? 'You nailed it.' : 'Good work—keep building.' }}</h1><p>You scored <strong>{{ result?.score ?? Math.round(score / questions.length * 100) }}%</strong>. Your revision schedule has been adjusted.</p><div class="score-strip"><div><strong>{{ result?.score ?? Math.round(score / questions.length * 100) }}%</strong><span>Score</span></div><div><strong>+{{ result?.xp_awarded ?? score * 40 }}</strong><span>XP earned</span></div><div><strong>{{ result?.mastery_changes.length || 0 }}</strong><span>Topics updated</span></div></div><p v-if="submitError" class="inline-error">{{submitError}}</p><div><button class="button" @click="index=0; done=false; checked=false; result=undefined">Review again</button><RouterLink class="button primary" to="/progress" @click="finishSession">Finish session →</RouterLink></div></section>
</div></template>
